version: "3.7"

services: 
  nodejs:
    image: node:lts
    working_dir: '/app'
    volumes: 
      - ./:/app
    command: bash -c "sh ./docker/nodejs/entrypoint.sh"
  
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./:/app
      - .docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
